### PR TITLE
Add Nix derivation

### PR DESCRIPTION
**Pull request by quchen**
Fire and forget Report generation. Woo!

### CODE REVIEW

**Comment by k4rtik** [comment]
Is it possible to specify a particular version of perl in the derivation? It currently fails with the following error:
```
expand < Prelude.hs | perl ../tools/splitAndIndexPgm >Prelude.verb
$* is no longer supported as of Perl 5.30 at ../tools/splitAndIndexPgm line 1.
make[1]: *** [Makefile:185: Prelude.verb] Error 255
rm Prelude.verb
make[1]: Leaving directory '/build/haskell-report/report'
make: *** [Makefile:5: default] Error 2
builder for '/nix/store/7pjqw9gazfdvd0a4axvv3hsd71j6zi85-haskell-report.drv' failed with exit code 2
error: build of '/nix/store/7pjqw9gazfdvd0a4axvv3hsd71j6zi85-haskell-report.drv' failed
```

**Comment by chessai** [comment]
This shouldn't be merged because nixpkgs isn't pinned. This is a symptom of what @k4rtik is saying.

**Comment by chessai** [comment]
I recommend pinning to 19.09 stable for now

**Comment by chessai** [comment]
Closing in favour of #6

**Pull request closed without merging**
